# Generated by Django 3.1 on 2020-08-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('information', models.TextField()),
                ('information_en', models.TextField(null=True)),
                ('information_tr', models.TextField(null=True)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['createDate'],
            },
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['createDate']},
        ),
    ]
