# Generated by Django 3.1 on 2020-08-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20200820_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(default='empty', editable=False, max_length=250, unique=True),
            preserve_default=False,
        ),
    ]
