# Generated by Django 3.1 on 2020-08-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='researchGroup',
            field=models.ManyToManyField(to='website.ResearchGroups'),
        ),
    ]
