# Generated by Django 3.1 on 2020-08-20 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20200821_0232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
