# Generated by Django 3.1 on 2020-08-20 23:40

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0012_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', models.ImageField(blank=True, default='profiles/user_default.jpg', upload_to=website.models.user_upload_to)),
                ('information', ckeditor.fields.RichTextField()),
                ('information_en', ckeditor.fields.RichTextField(null=True)),
                ('information_tr', ckeditor.fields.RichTextField(null=True)),
                ('linkedin', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('researchGroup', models.ManyToManyField(to='website.ResearchGroups')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
