# Generated by Django 3.1 on 2020-08-21 13:25

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20200821_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('year', models.DateField()),
                ('information', ckeditor_uploader.fields.RichTextUploadingField()),
                ('information_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('information_tr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('links', ckeditor.fields.RichTextField()),
                ('pdf', models.FileField(upload_to='')),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('information', ckeditor_uploader.fields.RichTextUploadingField()),
                ('information_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('information_tr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('link', models.CharField(max_length=255)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_tr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('excerpt', models.TextField()),
                ('excerpt_en', models.TextField(null=True)),
                ('excerpt_tr', models.TextField(null=True)),
                ('duration', models.CharField(max_length=50)),
                ('draft', models.BooleanField(default=False)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('involvedPeople', models.ManyToManyField(to='website.UserProfile')),
                ('researchGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Project', to='website.researchgroups')),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
    ]
