# Generated by Django 3.1 on 2020-08-21 13:28

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_project_publication_resource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_tr', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(editable=False, max_length=250, unique=True)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('content_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('content_tr', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('excerpt', models.TextField()),
                ('excerpt_en', models.TextField(null=True)),
                ('excerpt_tr', models.TextField(null=True)),
                ('duration', models.CharField(max_length=50)),
                ('draft', models.BooleanField(default=False)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('updateDate', models.DateTimeField(auto_now=True)),
                ('involvedPeople', models.ManyToManyField(to='website.UserProfile')),
                ('researchGroup', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Research', to='website.researchgroups')),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
    ]
